name = "PollaLand"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83b57d0ac1508add45e7276517ac5b68a2e99ea85565fa3243eb59c93406eb9a"

[versions]
forge = "40.3.0"
minecraft = "1.18.2"
