name = "PollaLand"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5be2c1470fd87f52a42d68964f6d388b11d8fdeacac45801841198d8ad796a09"

[versions]
forge = "40.3.0"
minecraft = "1.18.2"
